jobs:
  test:
    executor:
      name: node/default
      tag: '14.12'
      steps:
        - checkout
        - node/install-packages
        - run:
          command: npm run test
orbs:
  node: circleci/node
  version: 2.1
  workflows:
    test_my_app:
      jobs:
        - test
