version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@0.0.10

workflows:
  node-tests:
    jobs:
      - node/test

workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
