version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git

jobs:
  build:
    docker:
      - image: circleci/node:14.12
        working_directory: ~/source
        steps:
          - checkout
          - run:
            npm install
          - run:
            npm test
